title: Olaf Kolkman (part 2)
description: >
  Olaf Kolkman has had a long career in networking and Open Source that
  led him to be working on Internet Technology, Policy and Advocacy at the
  Internet Society. In September 2025, we had a long conversation with him.

  In this second part of our discussion, we discussed the Internet
  Society (ISOC) and managing volunteer organisations.
file: the_underbar-10-olaf-kolkman-part2.mp3
cast:
- BOOK
- OLAF
- SJN
- OALDERS
recorded: 2025-09-10
published: 2026-09-20 19:30
editors:
- BOOK
thanks:
- TPRF-Zoom-Bruce
syndication:
