title: A tangent about the Perl Toolchain Summit
description: >
  As preparations are underway for the Perl Toolchain Summit 2026,
  this short episode is the last excerpt recorded during PTS 2025 (as
  a tangent during the CPAN Testers interview, published as episode 6).
  BooK starts by explaining the selection process for the Perl Toolchain
  and some of the history, and then Doug, Ruth, Breno and Ferki reminisce
  about what makes the event so special.
file: the_underbar-8-a-PTS-tangent.mp3
cast:
- BOOK
- PREACTION
- GEEKRUTH
- GARU
- FERKI
recorded: 2025-05-04
published: 2025-12-29 16:00
editors:
- BOOK
thanks:
- SJN-PTS2025
syndication:
  apple: https://podcasts.apple.com/us/podcast/a-tangent-about-the-perl-toolchain-summit/id1821292042?i=1000743065282
  castbox: https://castbox.fm/episode/Episode-8---A-tangent-about-the-Perl-Toolchain-Summit-id6649076-id886934074
  pocketcasts: https://pocketcasts.com/podcast/the-underbar/700902d0-2cb8-013e-d33f-0eeccf47baff/a-tangent-about-the-perl-toolchain-summit/28d0be3c-b372-49ab-843d-f72c5eb725c2
  podcast_index: https://podcastindex.org/podcast/7377089?episode=47546913040
  podchaser: https://www.podchaser.com/podcasts/the-underbar-5970261/episodes/a-tangent-about-the-perl-toolc-277658924
  podlink: https://pod.link/1821292042/episode/aHR0cHM6Ly91bmRlcmJhci5jcGFuLmlvL2VwaXNvZGVzLzgvdGhlX3VuZGVyYmFyLTgtYS1QVFMtdGFuZ2VudC5tcDM
  spotify: https://open.spotify.com/episode/0i8G8FiK6IWyrc7sMhRXrN
