title: A tangent about the Perl Toolchain Summit
description: >
  As preparations are underway for the Perl Toolchain Summit 2026,
  this short episode is the last excerpt recorded during PTS 2025 (as
  a tangent during the CPAN Testers interview, published as episode 6).
  BooK starts by explaining the selection process for the Perl Toolchain
  and some of the history, and then Doug, Ruth, Breno and Ferki reminisce
  about what makes the event so special.
file: the_underbar-8-a-PTS-tangent.mp3
cast:
- BOOK
- PREACTION
- GEEKRUTH
- GARU
- FERKI
recorded: 2025-05-04
published: 2025-12-29 16:00
editors:
- BOOK
thanks:
- SJN-PTS2025
