title: The Cyber Resilience Act
description: >
  During the Perl Toolchain Summit 2025, Salve Nilsen and I had a long
  conversation about the CRA and Steward Organizations. We thought it
  would be great to record another, to reach a larger audience with
  this topic. So we invited Olaf Alders and Julien Fiegehenn to join us,
  and pressed the record button.
file: the_underbar-4-cra-with-sjn.mp3
cast:
- BOOK
- SJN
- OALDERS
- SIMBABQUE
recorded: 2025-08-06
published: 2025-09-07 02:00
editors:
- BOOK
thanks:
- TPRF-Zoom
links:
