title: The Cyber Resilience Act
description: >
  During the Perl Toolchain Summit 2025, Salve Nilsen and I had a long
  conversation about the CRA and Steward Organizations. We thought it
  would be great to record another, to reach a larger audience with
  this topic. So we invited Olaf Alders and Julien Fiegehenn to join us,
  and pressed the record button.
file: the_underbar-4-cra-with-sjn.mp3
cast:
- BOOK
- SJN
- OALDERS
- SIMBABQUE
recorded: 2025-08-06
published: 2025-09-07 02:00
editors:
- BOOK
thanks:
- TPRF-Zoom
syndication:
  apple: https://podcasts.apple.com/us/podcast/the-underbar-episode-4-the-cyber-resilience-act/id1821292042
  castbox: https://castbox.fm/episode/The-Underbar%2C-episode-4%3A-The-Cyber-Resilience-Act-id6649076-id843710669
  pocketcasts: https://pocketcasts.com/podcast/the-underbar/700902d0-2cb8-013e-d33f-0eeccf47baff/the-underbar-episode-4-the-cyber-resilience-act/302dd0c1-37a6-406c-9a1c-40c4151a31f5
  podcast_index: https://podcastindex.org/podcast/7377089?episode=42194929361
  podchaser: https://www.podchaser.com/podcasts/the-underbar-5970261/episodes/the-underbar-episode-4-the-cyb-264888667
  podlink: https://pod.link/1821292042/episode/aHR0cHM6Ly91bmRlcmJhci5jcGFuLmlvL2VwaXNvZGVzLzQvdGhlX3VuZGVyYmFyLTQtY3JhLXdpdGgtc2puLm1wMw
  spotify: https://open.spotify.com/episode/7goGbn0ShEQy4YS1HDHToI
