title: CPAN Testers
description: >
  During the Perl Toolchain Summit 2025 in Leipzig, we interviewed the
  CPAN Testers team. They told us about the history of the project,
  its recent problems, and how a new team formed around its (then)
  lone maintainer. They also told us about their plans for the future.
file: the_underbar-6-cpan-testers.mp3
cast:
- BOOK
- PREACTION
- GEEKRUTH
- FERKI
- GARU
recorded: 2025-05-04
published: 2025-10-10 11:30
editors:
- BOOK
thanks:
- SJN-PTS2025
syndication:
  apple: https://podcasts.apple.com/us/podcast/cpan-testers/id1821292042?i=1000731150996
  castbox: https://castbox.fm/episode/Episode-6---CPAN-Testers-id6649076-id855406123
  pocketcasts: https://pocketcasts.com/podcast/the-underbar/700902d0-2cb8-013e-d33f-0eeccf47baff/cpan-testers/13763d14-c2e2-4489-b6d6-c34b5de10219
  podcast_index: https://podcastindex.org/podcast/7377089?episode=43605114596
  podchaser: https://www.podchaser.com/podcasts/the-underbar-5970261/episodes/cpan-testers-268704662
  podlink: https://pod.link/1821292042/episode/aHR0cHM6Ly91bmRlcmJhci5jcGFuLmlvL2VwaXNvZGVzLzYvdGhlX3VuZGVyYmFyLTYtY3Bhbi10ZXN0ZXJzLm1wMw
  spotify: https://open.spotify.com/episode/5fC6zHBi24NzOWIrxh1CjB
