title: Test::Smoke
description: >
  During the Perl Toolchain Summit 2025 in Leipzig, we interviewed
  Merijn Brand, Test::Smoke's founder, and Thibault Duponchelle, its new
  maintainer following the passing of Abe Timmerman, about the history
  of the project, and how to contribute to it.
file: the_underbar-5-test-smoke.mp3
cast:
- BOOK
- CONTRA
- HMBRAND
recorded: 2025-05-04
published: 2025-09-26 14:00
editors:
- CONTRA
thanks:
- SJN-PTS
syndication:
  apple: https://podcasts.apple.com/us/podcast/the-underbar/id1821292042
  castbox: https://castbox.fm/episode/Episode-5---Test%253A%253ASmoke-id6649076-id850960521
  pocketcasts: https://pocketcasts.com/podcast/the-underbar/700902d0-2cb8-013e-d33f-0eeccf47baff/testsmoke/885d0135-89d2-427e-85b7-ac73f6992b04
  podcast_index: 
  podchaser: 
  podlink: https://pod.link/1821292042/episode/aHR0cHM6Ly91bmRlcmJhci5jcGFuLmlvL2VwaXNvZGVzLzUvdGhlX3VuZGVyYmFyLTUtdGVzdC1zbW9rZS5tcDM
  spotify: https://open.spotify.com/episode/4AVKBqm1a6rwAaxShHUIy7
