title: Test::Smoke
description: >
  During the Perl Toolchain Summit 2025 in Leipzig, we interviewed
  Merijn Brand, Test::Smoke's founder, and Thibault Duponchelle, its new
  maintainer following the passing of Abe Timmerman, about the history
  of the project, and how to contribute to it.
file: the_underbar-4-test-smoke.mp3
cast:
- BOOK
- CONTRA
- HMBRAND
recorded: 2025-05-04
published: 2025-09-26 14:00
editors:
- CONTRA
thanks:
- SJN-PTS
