title: Olaf Kolkman (part 1)
description: >
  Olaf Kolkman has had a long career in networking and Open Source that
  led him to be working on Internet Technology, Policy and Advocacy at the
  Internet Society. In September 2025, we had a long conversation with him.

  In this first part, we discussed his involvement
  with Perl, DNSSEC and NLnet Labs.
file: the_underbar-9-olaf-kolkman-part1.mp3
cast:
- BOOK
- OALDERS
- SJN
- OLAF
recorded: 2025-09-10
published: 2026-02-28 23:55
editors:
- BOOK
thanks:
- TPRF-Zoom-BGRAY
syndication:
  apple: https://podcasts.apple.com/us/podcast/olaf-kolkman-part-1/id1821292042?i=1000752125632
  castbox: https://castbox.fm/episode/Episode-9---Olaf-Kolkman-(part-1)-id6649076-id912007364
  pocketcasts: https://pocketcasts.com/podcast/the-underbar/700902d0-2cb8-013e-d33f-0eeccf47baff/olaf-kolkman-part-1/042effd2-2841-4606-8be3-13cddeca4a8c
  podcast_index: https://podcastindex.org/podcast/7377089?episode=50930501432
  podchaser: https://www.podchaser.com/podcasts/the-underbar-5970261/episodes/olaf-kolkman-part-1-284632218
  podlink: https://pod.link/1821292042/episode/aHR0cHM6Ly91bmRlcmJhci5jcGFuLmlvL2VwaXNvZGVzLzkvdGhlX3VuZGVyYmFyLTktb2xhZi1rb2xrbWFuLXBhcnQxLm1wMw
  spotify: https://open.spotify.com/episode/504uoTioVFBs0aTxy4LAkV
