title: Olaf Kolkman (part 1)
description: >
  Olaf Kolkman has had a long career in open source.
  In this first part, we discussed his involvement
  with Perl, DNSSEC and NLnet Labs.
file: the_underbar-9-olaf-kolkman-part1.mp3
cast:
- BOOK
- OALDERS
- SJN
- OLAF
recorded: 2025-09-10
published: 2026-02-28 23:55
editors:
- BOOK
thanks:
- TPRF-Zoom
