title: Perl 42
description: >
  The next version of Perl is going to be v5.42.0. Or maybe 42.0?
  Listen to Perl leaders arguing about what version numbers represent,
  and what it means to change one. (This is part two of a longer
  conversation started in the previous episode.)
file: the_underbar-2-perl-42.mp3
cast:
- BOOK
- OALDERS
- ARISTOTLE
- NEILB
- JESSE
- RJBS
recorded: 2025-02-28
published: 2025-06-13 12:00
editors:
- CONTRA
thanks:
- TPRF-Zoom
syndication:
  apple: https://podcasts.apple.com/us/podcast/the-underbar-episode-2-perl-42/id1821292042?i=1000713303902
  castbox: https://castbox.fm/episode/id6649076-id819849967
  podlink: https://pod.link/1821292042/episode/aHR0cHM6Ly91bmRlcmJhci5jcGFuLmlvL2VwaXNvZGVzLzIvdGhlX3VuZGVyYmFyLTItcGVybC00Mi5tcDM
  podcast_index: https://podcastindex.org/podcast/7377089?episode=38675738791
  spotify: https://open.spotify.com/episode/6LFg9KlNsR9fTKGTrFQGg7
