title: The New Perl Logo
description: >
  This episode was an experiment: how hard can it be to record a podcast?
  Find a topic (the new Perl logo), a few people who have something to
  say about it, schedule a meeting, hit record, and presto, you are
  now a podcaster. And because it was an experiment, we numbered it 0.
file: the_underbar-0-a-new-logo-for-perl.mp3
cast:
- BOOK
- OALDERS
- CONTRA
- BMENEG
- INGY
- RJBS
- SMONFF
recorded: 2025-01-10
published: 2025-01-17 20:00
editors:
- CONTRA
thanks:
- TPRF-Zoom
syndication:
  apple: https://podcasts.apple.com/us/podcast/the-underbar-episode-0-the-new-perl-logo/id1821292042?i=1000713303982
  castbox: https://castbox.fm/episode/id6649076-id819849963
  podcast_index: https://podcastindex.org/podcast/7377089?episode=38675738776
  podlink: https://pod.link/1821292042/episode/aHR0cHM6Ly91bmRlcmJhci5jcGFuLmlvL2VwaXNvZGVzLzAvdGhlX3VuZGVyYmFyLTAtYS1uZXctbG9nby1mb3ItcGVybC5tcDM
  spotify: https://open.spotify.com/episode/3GIEgdMJM7RJpoWhUx3Sni
