title: The New Perl Logo
description: >
  This episode was an experiment: how hard can it be to record a podcast?
  Find a topic (the new Perl logo), a few people who have something to
  say about it, schedule a meeting, hit record, and presto, you are
  now a podcaster. And because it was an experiment, we numbered it 0.
file: the_underbar-0-a-new-logo-for-perl.mp3
cast:
- BOOK
- OALDERS
- CONTRA
- BMENEG
- INGY
- RJBS
- SMONFF
recorded: 2025-01-10
published: 2025-01-17 20:00
editors:
- CONTRA
thanks:
- TPRF-Zoom
