title: Perl Leadership
description: >
  For this episode, we assembled a cast of Perl leaders, and talked
  about Perl versions. At the end of the scheduled time, we hadn't
  started discussing the planned controversial topic, so we kept
  talking, and split the episode in two parts. To be continued...
file: the_underbar-1-perl-leadership.mp3
cast:
- BOOK
- OALDERS
- ARISTOTLE
- NEILB
- JESSE
- RJBS
recorded: 2025-02-28
published: 2025-05-15 14:00
editors:
- CONTRA
thanks:
- TPRF-Zoom
