title: Perl Leadership
description: >
  For this episode, we assembled a cast of Perl leaders, and talked
  about Perl versions. At the end of the scheduled time, we hadn't
  started discussing the planned controversial topic, so we kept
  talking, and split the episode in two parts. To be continued...
file: the_underbar-1-perl-leadership.mp3
cast:
- BOOK
- OALDERS
- ARISTOTLE
- NEILB
- JESSE
- RJBS
recorded: 2025-02-28
published: 2025-05-15 14:00
editors:
- CONTRA
thanks:
- TPRF-Zoom-basic
syndication:
  apple: https://podcasts.apple.com/us/podcast/the-underbar-episode-1-perl-leadership/id1821292042?i=1000713303956
  castbox: https://castbox.fm/episode/id6649076-id819849965
  pocketcasts: https://pocketcasts.com/podcast/the-underbar/700902d0-2cb8-013e-d33f-0eeccf47baff/the-underbar-episode-1-perl-leadership/a7f14571-f8de-487c-ae3e-cc53adbfbf99
  podcast_index: https://podcastindex.org/podcast/7377089?episode=38675738779
  podchaser: https://www.podchaser.com/podcasts/the-underbar-5970261/episodes/the-underbar-episode-1-perl-le-251474424
  podlink: https://pod.link/1821292042/episode/aHR0cHM6Ly91bmRlcmJhci5jcGFuLmlvL2VwaXNvZGVzLzEvdGhlX3VuZGVyYmFyLTEtcGVybC1sZWFkZXJzaGlwLm1wMw
  spotify: https://open.spotify.com/episode/6LFg9KlNsR9fTKGTrFQGg7
