title: MetaCPAN
description: >
  During the Perl Toolchain Summit 2025 in Leipzig, we interviewed
  the MetaCPAN team about the history of the project, how it's managed
  and where it's going to.
file: the_underbar-3-metacpan.mp3
cast:
- BOOK
- OALDERS
- MICKEY
- SSORICHE
- HAARG
recorded: 2025-05-04
published: 2025-07-11 14:00
editors:
- BOOK
thanks:
- SJN-PTS
syndication:
  apple: https://podcasts.apple.com/us/podcast/the-underbar-episode-3-metacpan/id1821292042?i=1000716826480
  episodes_fm: https://episodes.fm/1821292042/episode/aHR0cHM6Ly91bmRlcmJhci5jcGFuLmlvL2VwaXNvZGVzLzMvdGhlX3VuZGVyYmFyLTMtbWV0YWNwYW4ubXAz
  podcast_index: https://podcastindex.org/podcast/7377089?episode=39763839889
  spotify: https://open.spotify.com/episode/7zm6C07DH9RQUR8YNUdOFW
