title: CPAN Security Group
description: >
  This is the last of the interviews recorded during the Perl Toolchain
  Summit 2025 in Leipzig, this time with the CPAN Security Group.
  We talked about how the group was formed, the security landscape for
  Perl and CPAN, and how volunteers are always needed.
file: the_underbar-7-cpan-sec.mp3
cast:
- BOOK
- SJN
- STIGTSP
- HMBRAND
- TIMLEGGE
- GARU
recorded: 2025-05-04
published: 2025-11-14 19:00
editors:
- BOOK
thanks:
- SJN-GARU-PTS2025
syndication:
  apple: https://podcasts.apple.com/us/podcast/cpan-security-group/id1821292042?i=1000736776201
  castbox: https://castbox.fm/episode/Episode-7---CPAN-Security-Group-id6649076-id872355187
  pocketcasts: https://pocketcasts.com/podcast/the-underbar/700902d0-2cb8-013e-d33f-0eeccf47baff/cpan-security-group/8af8fe6e-0a71-417d-9825-274bb4738633
  podcast_index: https://podcastindex.org/podcast/7377089?episode=45161396328
  podchaser: https://www.podchaser.com/podcasts/the-underbar-5970261/episodes/cpan-security-group-273169543
  podlink: https://pod.link/1821292042/episode/aHR0cHM6Ly91bmRlcmJhci5jcGFuLmlvL2VwaXNvZGVzLzcvdGhlX3VuZGVyYmFyLTctY3Bhbi1zZWMubXAz
  spotify: https://open.spotify.com/episode/1XQu4kQ2OX51ImZTSCGqVF
